use_frameworks!

def shared_pods
  pod 'MapboxDirections.swift', :git => 'https://github.com/mapbox/MapboxDirections.swift.git', :commit => '1e5802b7dc5628b04b54bfc2444ea8e6c882e086'
  pod 'MapboxNavigation.swift', :path => '..'
  pod 'Mapbox-iOS-SDK', '~> 3.4'
end

target 'Example-Swift' do
  platform :ios, '8.0'
  shared_pods
end

target 'Example-Objective-C' do
  platform :ios, '8.0'
  shared_pods
end
