version: 2

workflows:
  version: 2
  default:
    jobs:
      - xcode-10
      - xcode-10-cocoapods-integration
      - xcode-9-examples-build-test

step-library:
  - &restore-cache
      restore_cache:
        keys:
          - carthage-cache-v1-{{ checksum "Cartfile.resolved" }}
          - carthage-cache-v1- # used if checksum fails

  - &restore-cache-cocoapods
      restore_cache:
        keys:
          - cp-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "MapboxCoreNavigationTests/CocoaPodsTest/PodInstall/Podfile.lock" }}
          - cp-cache-v1-{{ arch }}-{{ .Branch }}
          - cp-cache-v1

  - &restore-cache-podmaster
      restore_cache:
        keys:
          - podmaster-cache

  - &save-cache
      save_cache:
        key: carthage-cache-v1-{{ checksum "Cartfile.resolved" }}
        paths:
          - Carthage

  - &save-cache-cocoapods
      save_cache:
        key: cp-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "MapboxCoreNavigationTests/CocoaPodsTest/PodInstall/Podfile.lock" }}
        paths:
          - MapboxCoreNavigationTests/CocoaPodsTest/PodInstall/Pods

  - &save-cache-podmaster
      save_cache:
        key: podmaster-cache
        paths:
          - "~/.cocoapods/repos/master"

  - &prepare
      run:
        name: Prepare
        command: |
          git submodule sync

  - &install-dependencies
      run:
        name: Install Dependencies
        command: carthage bootstrap --platform ios --cache-builds --configuration Release --no-use-binaries

  - &build-test-MapboxCoreNavigation
      run:
        name: Build and Test MapboxCoreNavigation
        command: |
          xcodebuild -sdk iphonesimulator -destination 'platform=iOS Simulator,id=9F32C487-FAEC-4ABE-B00D-159EC007E50D' -project MapboxNavigation.xcodeproj -scheme MapboxCoreNavigation clean build test | xcpretty

  - &build-MapboxNavigation
      run:
        name: Build MapboxNavigation
        command: |
          xcodebuild -sdk iphonesimulator -destination 'platform=iOS Simulator,id=9F32C487-FAEC-4ABE-B00D-159EC007E50D' -project MapboxNavigation.xcodeproj -scheme MapboxNavigation clean build | xcpretty

  - &build-Example-Obj-C
      run:
        name: Build and Test Example-Objective-C
        command: |
          xcodebuild -sdk iphonesimulator -destination 'platform=iOS Simulator,id=9F32C487-FAEC-4ABE-B00D-159EC007E50D' -project MapboxNavigation.xcodeproj -scheme Example-Objective-C clean build test | xcpretty

  - &build-Example-Swift
      run:
        name: Build and Test Example-Swift
        command: |
          xcodebuild -sdk iphonesimulator -destination 'platform=iOS Simulator,id=9F32C487-FAEC-4ABE-B00D-159EC007E50D' -project MapboxNavigation.xcodeproj -scheme Example-Swift clean build test | xcpretty

  - &cocoapods-integration-test
      run:
        name: CocoaPods integration test
        command: |
          cd MapboxCoreNavigationTests/CocoaPodsTest/PodInstall
          pod install
          xcodebuild -workspace PodInstall.xcworkspace/ -scheme PodInstall -destination 'platform=iOS Simulator,id=9F32C487-FAEC-4ABE-B00D-159EC007E50D' clean build | xcpretty

jobs:
  xcode-10:
    macos:
      xcode: "10.0.0"
    environment:
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - checkout
      - *prepare
      - *restore-cache
      - *install-dependencies
      - *build-test-MapboxCoreNavigation
      - *build-MapboxNavigation
      - *save-cache

  xcode-10-cocoapods-integration:
    macos:
      xcode: "10.0.0"
    environment:
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - checkout
      - *restore-cache-podmaster
      - *restore-cache-cocoapods
      - *cocoapods-integration-test
      - *save-cache-cocoapods
      - *save-cache-podmaster

  xcode-9-examples-build-test:
    macos:
      xcode: "9.4.1"
    environment:
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - checkout
      - *prepare
      - *restore-cache
      - *install-dependencies
      - *build-Example-Obj-C
      - *build-Example-Swift
      - *save-cache
