codecov:
  require_ci_to_pass: false
  notify:
    wait_for_ci: false

ignore:
  - "Example"
  - "MapboxNavigationTests"
  - "MapboxCoreNavigationTests"
  - "MapboxCoreNavigationIntegrationTests"
  - "TestHelper"
  - "Sources/MapboxNavigation/LanesStyleKit.swift"

coverage:
  status:
    project:
      default:
        threshold: 1%
    patch: false

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes
