platform :ios, '9.0'
use_frameworks!

target 'PodInstall' do
  pod 'MapboxGeocoder.swift', '~> 0.6.0'
  # The branch of MapboxNavigation and MapboxNavigationUI will be replaced by Bitrise to use the current branch.
  pod 'MapboxNavigationUI.swift', :git => 'https://github.com/mapbox/MapboxNavigation.swift.git', :branch => 'BRANCH_NAME'
  pod 'MapboxNavigation.swift', :git => 'https://github.com/mapbox/MapboxNavigation.swift.git', :branch => 'BRANCH_NAME'
  pod 'OSRMTextInstructions', :git => 'https://github.com/Project-OSRM/osrm-text-instructions.swift', :commit => 'bdd962bf5593f951bbbbd26435f732a829dacda7'
end
