#import <Foundation/Foundation.h>


extern NSString *const MBRouteControllerProgressDidChangeNotificationProgressKey;
extern NSString *const MBRouteControllerProgressDidChangeNotificationLocationKey;
extern NSString *const MBRouteControllerProgressDidChangeNotificationSecondsRemainingOnStepKey;

extern NSString *const MBRouteControllerAlertLevelDidChangeNotificationRouteProgressKey;
extern NSString *const MBRouteControllerAlertLevelDidChangeNotificationDistanceToEndOfManeuverKey;

extern NSString *const MBRouteControllerNotificationLocationKey;
extern NSString *const MBRouteControllerNotificationRouteKey;
extern NSString *const MBRouteControllerNotificationErrorKey;

extern NSString *const MBRouteControllerNotificationProgressDidChange;
extern NSString *const MBRouteControllerAlertLevelDidChange;
extern NSString *const MBRouteControllerWillReroute;
extern NSString *const MBRouteControllerDidReroute;
extern NSString *const MBRouteControllerDidFailToReroute;
