#import <Foundation/Foundation.h>


extern NSString *const MBRouteControllerProgressDidChangeNotificationProgressKey;
extern NSString *const MBRouteControllerProgressDidChangeNotificationLocationKey;
extern NSString *const MBRouteControllerProgressDidChangeNotificationSecondsRemainingOnStepKey;
extern NSString *const MBRouteControllerProgressDidChangeNotificationIsFirstAlertForStepKey;

extern NSString *const MBRouteControllerAlertLevelDidChangeNotificationRouteProgressKey;
extern NSString *const MBRouteControllerAlertLevelDidChangeNotificationDistanceToEndOfManeuverKey;

extern NSString *const MBRouteControllerNotificationShouldRerouteKey;

extern NSString *const MBRouteControllerNotificationProgressDidChange;
extern NSString *const MBRouteControllerAlertLevelDidChange;
extern NSString *const MBRouteControllerShouldReroute;
