platform :ios, '9.0'

inhibit_all_warnings!
use_frameworks!

pre_install do |installer|
# workaround for #3289
Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
end

target 'PodInstall' do
  # The branch of MapboxNavigation and MapboxNavigation will be replaced by Bitrise to use the current branch.
  pod 'MapboxNavigation', :git => 'GIT_REPO_URL', :branch => 'BRANCH_NAME'
  pod 'MapboxCoreNavigation', :git => 'GIT_REPO_URL', :branch => 'BRANCH_NAME'
  pod 'MapboxDirections.swift', :git => 'git@github.com:mapbox/MapboxDirections.swift.git', :branch => 'return-response'
  pod 'MapboxNavigationNative', :podspec => 'https://s3.amazonaws.com/mapbox/mapbox-navigation-native/ios/builds/MapboxNavigationNative.podspec'
end

